// actionTypes.js
export const EDIT_ACCORDION_ITEM = 'EDIT_ACCORDION_ITEM';
export const DELETE_ACCORDION_ITEM = 'DELETE_ACCORDION_ITEM';

export const SEARCH_ACCORDION_ITEM = "SEARCH_ACCORDION_ITEM";
export const CLEAR_ACCORDION_ITEM = "CLEAR_ACCORDION_ITEM";

